### ISSUE TITLE
\(x, y) -> z

### ISSUE THREAD

**Issue by cblp** [bmillwood/pointfree#12] opened 2015-09-23 12:36 UTC
```
$ pointfree -v '\(x, y) -> z'
```

Expected

```
Transformed to pointfree style:
...
const z
```

Got

```
Transformed to pointfree style:
ap (ap (const . const) fst) snd
Optimized expression:
ap (ap (const . const) fst) snd
ap const snd
id
```

**Comment by cblp** [comment] 2015-09-23 12:37
But
```
$ pointfree -v '\(x, z) -> y'
Transformed to pointfree style:
ap (const (const y) . fst) snd
Optimized expression:
ap (const (const y) . fst) snd
uncurry (const (const y))
const y . snd
const y
```

**Comment by bmillwood** [comment] 2015-10-03 14:21
Curious. Unfortunately I only maintain pointfree, I didn't write it, and I don't think I understand it well enough to know what's going on here.

**Comment by akiomik** [comment] 2015-10-10 17:17
In this case, the following lines are the cause.

https://github.com/bmillwood/pointfree/blob/master/Plugin/Pl/Transform.hs#L96-L99

Similarly, this problem also occurs in the following case:

```
$ pointfree -v '\(x:y) -> z'
Transformed to pointfree style:
ap (ap (const . const) head) tail
Optimized expression:
ap (ap (const . const) head) tail
ap const tail
id
```

**Comment by jFransham** [comment] 2016-11-08 15:21
Fixed in PR https://github.com/bmillwood/pointfree/issues/19

**Closed** 2017-03-11 16:34 UTC
